### ISSUE TITLE
Documentation cannot be generated for json schema based lib gen

### ISSUE THREAD

**Issue by ledouxpl** [Duologic/crdsonnet#1]
I am trying to generate the documentation libs generated through `fromSchema` according to the example found in the [README.md](https://github.com/Duologic/crdsonnet#documentation).

Unfortunately, `doc-util` fails when calling `renderFiles`:

```shell
RUNTIME ERROR: No such field: name
        <std>:775:15-42 thunk <val> from <function <format_codes_obj>>
        <std>:780:27-30 thunk from <thunk <s> from <function <format_codes_obj>>>
        <std>:604:22-25 thunk from <function <format_code>>
        <std>:604:9-26  function <format_code>
        <std>:780:15-50 thunk <s> from <function <format_codes_obj>>
        <std>:785:24-25 thunk from <thunk <s_padded> from <function <format_codes_obj>>>
        <std>:492:30-33 thunk from <thunk from <function <pad_left>>>
        <std>:492:19-34 thunk from <function <pad_left>>
        <std>:488:11-12 thunk from <function <padding>>
        <std>:484:12-13 function <aux>
        ...
        <std>:492:7-38  function <pad_left>
        <std>:785:15-35 thunk <s_padded> from <function <format_codes_obj>>
        <std>:786:51-59 thunk from <function <format_codes_obj>>
        <std>:786:11-60 function <format_codes_obj>
        <std>:791:7-43  function <anonymous>
        <std>:249:7-23  function <anonymous>
        vendor/github.com/jsonnet-libs/docsonnet/doc-util/render.libsonnet:97:6-38
        vendor/github.com/jsonnet-libs/docsonnet/doc-util/render.libsonnet:356:21-48    object <anonymous>
        Field "README.md"
        During manifestation
```

I generate the doc by invoking jsonnet through the following command:

```shell
jsonnet -J vendor -S -c -m docs docs.libsonnet
```

```jsonnet
// docs.libsonnet

local d = import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet';

local tye = import './main.libsonnet';

d.render(tye)
```

```jsonnet
// main.libsonnet

local crdsonnet = import 'github.com/Duologic/crdsonnet/crdsonnet/main.libsonnet';
local schemaDB = import 'github.com/Duologic/crdsonnet/crdsonnet/schemadb.libsonnet';

local db = schemaDB.add(import './tye.schema.json');

local schema = db['http://microsoft.com/dotnet/tye.schema.json'];

crdsonnet.fromSchema('tye', schema, db)
```

The json schema can be found here: https://raw.githubusercontent.com/dotnet/tye/main/src/schema/tye-schema.json

I traced a bit through [tye-gen/vendor/doc-util/render.libsonnet](https://github.com/jsonnet-libs/docsonnet/blob/master/doc-util/render.libsonnet) and the output of the [prepare function](https://github.com/jsonnet-libs/docsonnet/blob/master/doc-util/render.libsonnet#L248) results in an object containing:

```json
{
    "functionSections": [],
    "objectSections": [
    // Removed for readability
    ],
    "sections": [
    // Removed for readability
    ],
    "subPackages": [],
    "values": []
}
```

It therefore fails straight away when calling [renderPackage](https://github.com/jsonnet-libs/docsonnet/blob/master/doc-util/render.libsonnet#L356) as it tries format the prepared package above using the `root.templates.package` defined as:

```jsonnet
    package: |||
      # package %(name)s

      %(content)s
    |||,
```

Indeed, the object does not contain a `name` key. It also does not contain a `content` key.

Note that I am able to workaround this issue by adding a bogus `name` and `content` field to the init object in the [prepare](https://github.com/jsonnet-libs/docsonnet/blob/master/doc-util/render.libsonnet#L327) function:

```jsonnet
      {
        name: 'root',
        content: '',
        functionSections: [],
        objectSections: [],

        sections:
          self.functionSections
          + self.objectSections,
        subPackages: [],
        values: [],
      }
```

Doing so, does generate the `README.md`:

```md
# package root

## Index

* [`obj tye`](#obj-tye)
  * [`fn withContainerEngine(value)`](#fn-tyewithcontainerengine)
  * [`fn withDashboardPort(value)`](#fn-tyewithdashboardport)
  ...
```

I am unsure if this is a bug,   if documentation generation of json schema generated libs is unsupported altogether, or if it is a usage mistake on my part.

**Comment by Duologic** [comment]
This is an excellent bug report. I have missed an important bit to make documentation rendering actually work.

For [docsonnet](https://github.com/jsonnet-libs/docsonnet) to work, we need to have a docstring for the root package `{ '#': d.package.new() }`. For the libraries that I've been building, I was configuring that on the library itself and missed that it wasn't part of the library yet.

One public example is [drone-libsonnet](https://github.com/Duologic/drone-libsonnet/blob/master/main.libsonnet), instead of directly exposing the rendered library, it restructures the library and provides the package docstring(s) there.

For the sake of keeping it simple, I'm going to update the `docs.libsonnet` in the README to include the package docstring, this should be sufficient to get it working.
